packages:
  - docs/
  - packages/*

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - unrs-resolver

overrides:
  # FIXME: avoid outdated dependencies introducing vulnerable undici
  "@codecov/bundler-plugin-core@1>@actions/core": npm:@actions/core@2
  "@codecov/bundler-plugin-core@1>@actions/github": npm:@actions/github@8
  "@mdit/plugin-alert": workspace:*
  "@mdit/plugin-align": workspace:*
  "@mdit/plugin-attrs": workspace:*
  "@mdit/plugin-container": workspace:*
  "@mdit/plugin-demo": workspace:*
  "@mdit/plugin-figure": workspace:*
  "@mdit/plugin-footnote": workspace:*
  "@mdit/plugin-icon": workspace:*
  "@mdit/plugin-img-lazyload": workspace:*
  "@mdit/plugin-img-mark": workspace:*
  "@mdit/plugin-img-size": workspace:*
  "@mdit/plugin-include": workspace:*
  "@mdit/plugin-inline-rule": workspace:*
  "@mdit/plugin-katex": workspace:*
  "@mdit/plugin-katex-slim": workspace:*
  "@mdit/plugin-mark": workspace:*
  "@mdit/plugin-mathjax-slim": workspace:*
  "@mdit/plugin-plantuml": workspace:*
  "@mdit/plugin-spoiler": workspace:*
  "@mdit/plugin-stylize": workspace:*
  "@mdit/plugin-sub": workspace:*
  "@mdit/plugin-sup": workspace:*
  "@mdit/plugin-tab": workspace:*
  "@mdit/plugin-tasklist": workspace:*
  "@mdit/plugin-tex": workspace:*
  "@mdit/plugin-uml": workspace:*
  vite@7: npm:rolldown-vite@7

patchedDependencies:
  "@vuepress/plugin-markdown-math": patches/@vuepress__plugin-markdown-math.patch
