packages:
  - docs/
  - packages/*

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  unrs-resolver: true

overrides:
  "@mdit/helper": workspace:*
  "@mdit/plugin-abbr": workspace:*
  "@mdit/plugin-alert": workspace:*
  "@mdit/plugin-align": workspace:*
  "@mdit/plugin-anchor": workspace:*
  "@mdit/plugin-attrs": workspace:*
  "@mdit/plugin-container": workspace:*
  "@mdit/plugin-demo": workspace:*
  "@mdit/plugin-dl": workspace:*
  "@mdit/plugin-embed": workspace:*
  "@mdit/plugin-emoji": workspace:*
  "@mdit/plugin-field": workspace:*
  "@mdit/plugin-figure": workspace:*
  "@mdit/plugin-footnote": workspace:*
  "@mdit/plugin-icon": workspace:*
  "@mdit/plugin-img-lazyload": workspace:*
  "@mdit/plugin-img-mark": workspace:*
  "@mdit/plugin-img-size": workspace:*
  "@mdit/plugin-include": workspace:*
  "@mdit/plugin-inline-rule": workspace:*
  "@mdit/plugin-ins": workspace:*
  "@mdit/plugin-katex": workspace:*
  "@mdit/plugin-katex-slim": workspace:*
  "@mdit/plugin-layout": workspace:*
  "@mdit/plugin-mark": workspace:*
  "@mdit/plugin-mathjax": workspace:*
  "@mdit/plugin-mathjax-slim": workspace:*
  "@mdit/plugin-plantuml": workspace:*
  "@mdit/plugin-ruby": workspace:*
  "@mdit/plugin-snippet": workspace:*
  "@mdit/plugin-spoiler": workspace:*
  "@mdit/plugin-stylize": workspace:*
  "@mdit/plugin-sub": workspace:*
  "@mdit/plugin-sup": workspace:*
  "@mdit/plugin-tab": workspace:*
  "@mdit/plugin-tasklist": workspace:*
  "@mdit/plugin-tex": workspace:*
  "@mdit/plugin-uml": workspace:*
  markdown-it: 15.0.1

cleanupUnusedCatalogs: true

enableGlobalVirtualStore: true

packageExtensions:
  # FIXME: This is a bug in mathjax
  "@mathjax/mathjax-newcm-font":
    peerDependencies:
      "@mathjax/src": ^4.1.2

  # FIXME: This is a bug in mathjax
  "@mathjax/mathjax-tex-font":
    peerDependencies:
      "@mathjax/src": ^4.1.2

  "@lerna-lite/version":
    peerDependencies:
      conventional-changelog-conventionalcommits: ^10.2.0

minimumReleaseAgeExclude:
  - "@oxfmt/*"
  - "@oxlint/*"
  - oxc-config-hope
  - oxfmt
  - oxlint

patchedDependencies:
  markdown-it-cjk-friendly@2.0.2: patches/markdown-it-cjk-friendly@2.0.2.patch
